apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-client
  labels:
    app: ubuntu-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-client
  template:
    metadata:
      labels:
        app: ubuntu-client
      name: ubuntu-client
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      nodeName: worker0
      containers:
      - name: hr-client
        image: gvafram3/mucache:client
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
