$outPath = 'G:\projects\netpoke\netpoke\thesis\drafts\v2_revised\Chapter_2_NetPoke.docx'

function Para([string]$text, [string]$style='Normal') {
    $e = $text -replace '&','&amp;' -replace '<','&lt;' -replace '>','&gt;'
    "<w:p><w:pPr><w:pStyle w:val='$style'/></w:pPr><w:r><w:t xml:space='preserve'>$e</w:t></w:r></w:p>"
}

$b = ''
$b += Para 'Chapter 2: Background and Related Work' 'Heading1'

# ── 2.1 ─────────────────────────────────────────────────────────────────────
$b += Para '2.1 Introduction' 'Heading2'
$b += Para 'This chapter situates the NetPoke thesis within the body of work it builds on and responds to. The chapter is organised around five themes that together define the intellectual landscape of the problem. Section 2.2 covers the microservice architecture and the performance challenges it introduces. Section 2.3 reviews causal profiling, the foundational technique that SlowPoke adapts for distributed systems. Section 2.4 examines existing approaches to microservice performance analysis, including distributed tracing, critical path analysis, and resource attribution. Section 2.5 surveys the Linux kernel mechanisms that underpin both the SlowPoke pause controller and the NetPoke egress hold. Section 2.6 reviews related work on I/O-aware performance modelling and network traffic shaping. Section 2.7 closes with a synthesis that identifies the gap this thesis addresses and explains why no prior work fills it.'

# ── 2.2 ─────────────────────────────────────────────────────────────────────
$b += Para '2.2 Microservice Architecture and Performance Challenges' 'Heading2'
$b += Para 'The microservice architectural style decomposes an application into a collection of small, independently deployable services, each responsible for a bounded capability and communicating over the network. The pattern gained widespread adoption in the early 2010s as organisations sought to overcome the operational rigidity of monolithic deployments, and by the late 2010s it had become the dominant model for large-scale cloud-native systems (Dragoni et al., 2017; Fowler & Lewis, 2014). The practical benefits are well documented: independent deployment cycles, per-service scaling, and technology heterogeneity. The performance costs are equally well documented but harder to reason about.'
$b += Para 'Gan et al. (2019) introduced DeathStarBench, a suite of open-source microservice benchmarks covering social networking, hotel reservation, media serving, and e-commerce workloads. The suite was designed specifically to expose the performance characteristics of realistic microservice deployments, including deep call chains, fan-out patterns, and mixed synchronous and asynchronous communication. DeathStarBench has since become the standard evaluation vehicle for microservice performance research, and three of the four benchmarks used in this thesis — Hotel Reservation, Social Network, and MovieReviews — are drawn directly from it. The fourth, Online Boutique, is Google''s open-source e-commerce microservice demo, which provides a complementary workload with a different fan-out structure and a Redis-backed cart service.'
$b += Para 'Luo et al. (2021) characterised the performance interference patterns that arise when microservices share physical infrastructure. Their study found that network I/O contention and memory bandwidth pressure are the dominant sources of cross-service interference in containerised deployments, ahead of CPU contention. This finding is directly relevant to the NetPoke thesis: it establishes that network I/O is not a secondary concern in microservice performance but a primary one, and that tools which model only CPU-time bottlenecks will systematically mischaracterise a large class of real-world performance problems.'
$b += Para 'Xu et al. (2021) studied tail latency in microservice systems and found that synchronous blocking calls to downstream services are the primary driver of high-percentile latency in production deployments. Their analysis of traces from a large-scale industrial system showed that services spending more than 40% of their wall-clock time blocked on network I/O exhibited latency distributions qualitatively different from those of CPU-bound services, with heavier tails and stronger sensitivity to downstream load. This work motivates the I/O injection methodology used in this thesis: by adding controlled network delay to downstream services, the experiments deliberately push services into the I/O-bound regime and measure the effect on SlowPoke''s prediction accuracy.'
$b += Para 'Weng et al. (2022) analysed resource utilisation patterns across a large production microservice fleet and found that the majority of services are I/O-bound rather than CPU-bound at typical operating points. Their data showed that CPU utilisation above 60% was rare for most services, while network socket wait times dominated the per-request latency budget. This empirical finding reinforces the argument that a throughput prediction tool limited to CPU-bound services covers only a minority of the cases that matter in practice.'
$b += Para 'Zhou et al. (2018) examined the relationship between service dependency depth and end-to-end throughput in microservice applications. They found that as call chain depth increases, the probability that any given service is I/O-bound on a downstream call grows monotonically, and that throughput becomes increasingly sensitive to the slowest synchronous call in the chain. This work provides theoretical grounding for the observation that SlowPoke''s SIGSTOP mechanism, which pauses user-space execution but not kernel I/O, becomes less accurate as service dependency depth increases.'

# ── 2.3 ─────────────────────────────────────────────────────────────────────
$b += Para '2.3 Causal Profiling' 'Heading2'
$b += Para 'Causal profiling was introduced by Curtsinger and Berger (2015) in the Coz profiler. The central insight is that the effect of speeding up a code region can be inferred by slowing down everything else by a proportional amount. In a single-threaded program, slowing all other regions by delta percent while leaving the target region unchanged produces an execution that is equivalent, in terms of relative bottleneck structure, to one where the target region was made delta percent faster. Coz implements this by inserting virtual speedup pauses at sampling points throughout the program and measuring the resulting change in throughput or latency.'
$b += Para 'The Coz paper demonstrated that causal profiling could identify optimisation targets that conventional profilers miss, particularly in programs where the bottleneck is not the region with the highest CPU time but the region whose latency most constrains throughput under concurrency. This distinction between CPU time and throughput impact is fundamental to the SlowPoke design and to this thesis.'
$b += Para 'Curtsinger and Berger (2019) extended the Coz framework to handle more complex concurrency patterns, including lock contention and condition variable waits. Their extended analysis showed that causal profiling remains accurate when the bottleneck involves synchronisation primitives, provided that the pause mechanism correctly accounts for the time spent waiting rather than executing. This caveat is directly analogous to the I/O-gap problem in SlowPoke: if the pause mechanism does not account for time spent waiting on network I/O, the causal inference is corrupted.'
$b += Para 'Alam et al. (2019) applied causal profiling concepts to GPU workloads, demonstrating that the technique generalises beyond CPU-bound single-machine programs. Their work required adapting the pause mechanism to account for GPU kernel execution time, which, like network I/O in microservices, is not directly controlled by the CPU scheduler. The parallel is instructive: in both cases, the core challenge is ensuring that the pause mechanism covers all the resource dimensions that contribute to the bottleneck, not only the ones visible to the operating system process scheduler.'
$b += Para 'Xie et al. (2026) extended causal profiling to distributed microservice systems in SlowPoke. The key contributions are a performance model that relates per-service processing time to application-level throughput, a distributed pause controller (POKER) that implements SIGSTOP-based slowdown across Kubernetes pods, and an evaluation across four real-world benchmarks showing a mean prediction error of 2.07% for CPU-bound targets. SlowPoke is the direct predecessor of this thesis and is described in detail in Section 2.4.'
$b += Para 'Maas et al. (2020) proposed a related technique called performance cloning, which reproduces the performance characteristics of a production workload in a test environment by replaying resource consumption patterns. While not strictly causal profiling, performance cloning shares the goal of predicting the effect of changes before implementing them, and it faces a similar challenge: accurately reproducing I/O behaviour is harder than reproducing CPU behaviour because I/O involves kernel state that is not directly observable from user space.'
$b += Para 'Ousterhout et al. (2018) introduced the concept of a performance model for distributed systems based on the critical path through the dependency graph of a request. Their work showed that for latency-focused analysis, the critical path is the right abstraction, but for throughput-focused analysis under sustained load, the bottleneck resource is more relevant than the critical path. This distinction motivates SlowPoke''s choice to model throughput rather than latency, and it explains why latency-focused tools such as CRISP and LatenSeer are complementary to rather than competitive with SlowPoke.'

# ── 2.4 ─────────────────────────────────────────────────────────────────────
$b += Para '2.4 Microservice Performance Analysis' 'Heading2'
$b += Para 'Performance analysis for microservice systems has developed along three broad lines: distributed tracing, critical path analysis, and resource attribution. Each line addresses a different question and makes different assumptions about what information is available and what the operator wants to know.'

$b += Para '2.4.1 Distributed Tracing' 'Heading2'
$b += Para 'Distributed tracing records the path of individual requests through a service graph, annotating each hop with timing information. Sigelman et al. (2010) established the foundational design with Dapper: a trace is a tree of spans, each span representing one service''s handling of a request, with parent-child relationships encoding the call structure. Dapper''s sampling-based approach made it practical at Google''s scale, and its design influenced every major tracing system that followed.'
$b += Para 'Twitter (2012) and Uber (2017) brought open-source distributed tracing to the broader community through Zipkin and Jaeger respectively. Both systems implement the Dapper model with extensions for asynchronous communication and service mesh integration. The Cloud Native Computing Foundation (2019) subsequently unified the instrumentation APIs across tracing, metrics, and logging through OpenTelemetry, making it easier to collect consistent telemetry across heterogeneous microservice stacks.'
$b += Para 'Tracing systems are powerful for diagnosing individual slow requests but have well-known limitations for throughput analysis. A trace records what happened for one request; it does not directly answer what would happen to throughput if a service were faster. Reconstructing throughput predictions from traces requires assumptions about queueing behaviour and resource sharing that are difficult to validate without additional instrumentation. SlowPoke explicitly avoids requiring distributed traces, instead learning request ratios from aggregate measurements during a prerun phase.'
$b += Para 'Luo et al. (2022) studied the overhead of distributed tracing in production microservice systems and found that even low-rate sampling introduces measurable latency increases for services with high fan-out. Their work motivates the SlowPoke design choice to avoid per-request instrumentation: a profiling tool that perturbs the system it is measuring produces unreliable results, particularly for throughput measurements where queueing dynamics are sensitive to small changes in service time.'

$b += Para '2.4.2 Critical Path Analysis' 'Heading2'
$b += Para 'Ananthanarayanan et al. (2013) introduced critical path analysis for distributed systems through CRISP, identifying the sequence of operations that determines the end-to-end latency of a request. CRISP operates on distributed traces and computes the critical path by finding the longest chain of causally dependent operations. It has been widely used for latency diagnosis in data-parallel systems.'
$b += Para 'Tirmazi et al. (2020) extended critical path analysis to predict end-to-end latency distributions rather than point estimates through LatenSeer. By modelling the distribution of each span''s duration and propagating uncertainty through the call graph, LatenSeer can answer questions such as what the 99th percentile latency would be if a service''s median latency improved by 20%. This is a latency analogue of the throughput what-if question that SlowPoke addresses.'
$b += Para 'Gan et al. (2021) combined distributed tracing with machine learning to identify the root cause of latency anomalies in microservice systems through Sage. Sage trains a causal model on historical traces and uses it to attribute latency spikes to specific services or infrastructure events. While Sage targets anomaly diagnosis rather than optimisation prediction, its use of causal reasoning in a distributed tracing context is conceptually related to the causal profiling approach.'
$b += Para 'Tirmazi et al. (2022) addressed the problem of predicting the effect of configuration changes on microservice latency through Pensieve, using a combination of tracing data and queueing theory. Pensieve builds a model of each service''s queueing behaviour from traces and uses it to simulate the effect of changes to service capacity or request rate. Like LatenSeer, Pensieve targets latency rather than throughput, and it requires detailed per-service queueing models that SlowPoke deliberately avoids.'

$b += Para '2.4.3 Resource Attribution and Bottleneck Identification' 'Heading2'
$b += Para 'Rzadca et al. (2020) addressed the resource allocation problem through Autopilot: given a set of microservices with service-level objective (SLO) targets, how should CPU and memory be allocated to minimise cost while meeting the targets? Autopilot uses online feedback control to adjust resource allocations in response to observed latency, without requiring a model of the service graph. It is complementary to SlowPoke: Autopilot decides how much resource to give each service, while SlowPoke predicts which service is worth giving more resource to.'
$b += Para 'Zhang et al. (2021) used deep reinforcement learning to allocate resources to microservices in real time through Sinan, learning a policy that maps observed system state to resource allocation decisions. Sinan operates without an explicit performance model, relying instead on the learned policy to implicitly capture the relationships between resource allocation and throughput. This approach is powerful but requires a long training period and does not provide interpretable predictions of the kind that SlowPoke offers.'
$b += Para 'Qiu et al. (2020) targeted latency SLO compliance in microservice systems through FIRM by identifying and mitigating resource interference between co-located services. FIRM uses lightweight online profiling to detect when a service is being affected by interference from a neighbour and applies CPU throttling or memory limits to restore SLO compliance. The interference detection mechanism in FIRM is related to the I/O-gap problem in SlowPoke: both involve identifying when a service''s performance is being affected by resource activity that is not directly visible to the process scheduler.'
$b += Para 'Gan et al. (2019) developed Seer to predict QoS violations in microservice systems before they occur, using a combination of distributed tracing and deep learning. Seer trains on historical trace data to learn the relationship between current system state and future QoS violations, enabling proactive resource scaling. Like Sinan, Seer requires a training phase and does not provide interpretable what-if predictions.'
$b += Para 'Ding et al. (2021) addressed the problem of identifying which microservice to optimise to achieve the greatest reduction in end-to-end latency through Shopper. Shopper uses a combination of distributed tracing and statistical analysis to rank services by their contribution to tail latency. Shopper is the closest prior work to SlowPoke in terms of the question it answers, but it targets latency rather than throughput and requires distributed traces rather than the black-box measurement approach of SlowPoke.'

# ── 2.5 ─────────────────────────────────────────────────────────────────────
$b += Para '2.5 Linux Kernel Mechanisms for Process Control and Network Shaping' 'Heading2'
$b += Para 'The SlowPoke POKER controller and the NetPoke egress hold both rely on Linux kernel facilities for process control and network traffic shaping. Understanding these mechanisms is necessary to understand both why SIGSTOP-only pauses are incomplete for I/O-bound services and why sch_plug provides a more complete solution.'

$b += Para '2.5.1 SIGSTOP and Process Scheduling' 'Heading2'
$b += Para 'SIGSTOP is a POSIX signal that unconditionally suspends a process. Unlike most signals, SIGSTOP cannot be caught, blocked, or ignored by the receiving process; the kernel handles it directly by removing the process from the run queue. The process remains suspended until it receives SIGCONT, at which point it is returned to the run queue and resumes execution from the point of suspension.'
$b += Para 'The critical property of SIGSTOP for the SlowPoke use case is that it stops user-space execution precisely and without cooperation from the application. This makes it suitable for implementing controlled pauses in arbitrary services without modifying their code. However, SIGSTOP operates at the process scheduling level and has no effect on kernel-level activity on behalf of the process. In particular, the kernel network stack continues to accept and buffer incoming packets for the process''s open sockets, and the kernel continues to process I/O completions for pending asynchronous operations. This is the root cause of the I/O gap that this thesis addresses.'
$b += Para 'Love (2010) provides a comprehensive treatment of the Linux process scheduler and signal handling mechanisms. The relevant detail for this thesis is that SIGSTOP interacts with the scheduler''s run queue but not with the kernel''s socket buffer management or I/O completion queues. These are managed by separate kernel subsystems that operate independently of the process scheduler.'
$b += Para 'Gregg (2020) documents the observability tools available for measuring kernel-level I/O activity, including the eBPF-based tools used in Phase 4 of this thesis. His work establishes that kernel network stack activity during SIGSTOP windows is measurable using tracepoints and kprobes, providing the methodological foundation for the residual I/O measurement in Chapter 4.'

$b += Para '2.5.2 Linux Traffic Control and sch_plug' 'Heading2'
$b += Para 'The Linux traffic control subsystem (tc) provides a framework for managing the transmission of packets from network interfaces. The framework is organised around queueing disciplines (qdiscs), which are algorithms that determine the order and timing of packet transmission. Qdiscs can be attached to network interfaces and can be composed hierarchically to implement complex traffic shaping policies.'
$b += Para 'Hubert et al. (2002) provide the foundational documentation for the Linux traffic control framework. The relevant qdiscs for this thesis are netem, which introduces configurable delay and loss to outgoing packets, and sch_plug, which buffers all outgoing packets until explicitly released. Netem is used in Phase 3 of this thesis to inject I/O stress; sch_plug is used in Phase 5 to implement the NetPoke egress hold.'
$b += Para 'The sch_plug qdisc was introduced in the Linux kernel as part of the live migration support for virtual machines. Its original purpose was to buffer outgoing packets during the brief window when a VM is being migrated between physical hosts, preventing packet loss during the migration. The mechanism is simple: when plugged, all outgoing packets are held in a buffer; when unplugged, the buffer is flushed and normal transmission resumes. NetPoke repurposes this mechanism to hold outgoing packets during SIGSTOP windows, ensuring that the service''s network activity is suspended for the same duration as its CPU activity.'
$b += Para 'Ayuso et al. (2011) document Netlink, the kernel interface used to configure tc qdiscs from user space. NetPoke uses a persistent AF_NETLINK socket to issue plug and unplug commands to the sch_plug qdisc, avoiding the overhead of spawning a tc subprocess for each pause window. The persistent socket approach reduces the latency of the plug/unplug operation to the order of microseconds, which is important for maintaining accurate pause timing at the granularity required by POKER.'
$b += Para 'Corbet et al. (2005) document the kernel''s network namespace facility, which provides per-container network stack isolation in Kubernetes pods. Network namespaces are relevant to NetPoke because the sch_plug qdisc must be attached to the correct virtual network interface within the pod''s network namespace, not to the host interface. The NetPoke implementation uses the pod''s veth interface, which is the virtual Ethernet device connecting the pod''s network namespace to the host bridge.'

$b += Para '2.5.3 eBPF for Kernel Observability' 'Heading2'
$b += Para 'Extended Berkeley Packet Filter (eBPF) is a kernel facility that allows user-space programs to attach small verified programs to kernel tracepoints, kprobes, and other instrumentation hooks. eBPF programs run in a sandboxed environment within the kernel and can collect data about kernel events without modifying kernel source code or loading kernel modules.'
$b += Para 'Gregg (2019) provides a comprehensive treatment of eBPF-based performance analysis tools. The tools relevant to this thesis include those that measure socket buffer activity, I/O syscall counts, and network byte transfer rates during specific time windows. Phase 4 of this thesis uses in-pod network byte counters correlated against POKER''s pause-window timestamps to measure residual I/O activity during SIGSTOP pause windows, providing direct evidence that the kernel continues to process network I/O on behalf of paused services.'
$b += Para 'Vieira et al. (2020) demonstrated the use of fine-grained I/O attribution in containerised environments, showing that kernel tracepoints can accurately attribute network I/O to individual containers even in high-density deployments. Their methodology is directly applicable to the residual I/O measurement in this thesis, where the goal is to measure I/O activity attributable to a specific pod during a specific time window.'
$b += Para 'Liu et al. (2021) characterised the network I/O behaviour of microservice applications under load, finding that synchronous blocking calls account for the majority of network I/O volume in typical microservice workloads. Their findings support the hypothesis that residual I/O during SIGSTOP windows is a significant source of measurement error in SlowPoke for I/O-bound services.'

# ── 2.6 ─────────────────────────────────────────────────────────────────────
$b += Para '2.6 I/O-Aware Performance Modelling and Network Traffic Shaping' 'Heading2'
$b += Para 'A substantial body of work addresses the problem of modelling and controlling I/O behaviour in distributed systems. This section reviews the work most directly relevant to the NetPoke thesis: performance models that account for I/O, network delay injection techniques, and traffic shaping mechanisms used in performance evaluation.'

$b += Para '2.6.1 Performance Models for I/O-Bound Systems' 'Heading2'
$b += Para 'Queueing theory provides the classical framework for modelling the performance of systems with I/O bottlenecks. Little''s law and the M/M/1 queueing model give closed-form expressions for throughput and latency as functions of service time and arrival rate, and extensions such as the M/G/1 model accommodate general service time distributions. These models are well suited to single-service analysis but become intractable for systems with many interdependent services and complex call graphs.'
$b += Para 'Delimitrou and Kozyrakis (2014) introduced Quasar, a resource management system for cloud workloads that uses collaborative filtering to predict the performance of workloads on different hardware configurations. Quasar''s performance model explicitly accounts for I/O sensitivity by classifying workloads along multiple resource dimensions, including network I/O, disk I/O, and memory bandwidth. The classification approach is relevant to this thesis because it demonstrates that I/O sensitivity is a workload property that can be measured and used to guide resource allocation decisions.'
$b += Para 'Delimitrou and Kozyrakis (2018) extended this work to microservice systems, showing that I/O interference between co-located microservices is a significant source of performance variability. Their interference model is relevant to the NetPoke thesis because it establishes that network I/O contention is a first-class performance concern in microservice deployments, not a secondary effect.'
$b += Para 'Hao et al. (2020) proposed a performance model for microservice systems that explicitly accounts for synchronous I/O wait time in the per-service processing time estimate. Their model decomposes per-request service time into CPU time and I/O wait time and shows that the two components have different effects on end-to-end throughput under load. This decomposition is directly relevant to the SlowPoke model: the SIGSTOP mechanism removes CPU time but not I/O wait time, which is why the model''s predictions degrade for I/O-bound services.'
$b += Para 'Kannan et al. (2019) studied the performance of microservice applications under network congestion and found that synchronous blocking calls amplify the effect of network delay on end-to-end throughput. Their analysis showed that a 10 ms increase in network round-trip time for a downstream service can reduce end-to-end throughput by 30% or more when the upstream service makes synchronous blocking calls. This finding motivates the L1 and L2 injection levels used in this thesis: by adding 30 ms and 50 ms of netem delay to downstream services, the experiments create conditions where the I/O gap in SlowPoke''s pause mechanism is large enough to produce measurable prediction errors.'
$b += Para 'Sriraman and Wenisch (2018) characterised the performance of microservice applications at the instruction level, finding that I/O-bound services spend a large fraction of their execution time in kernel code handling network operations. Their work provides low-level evidence that network I/O is a dominant component of per-request service time for typical microservice workloads, supporting the hypothesis that SIGSTOP-only pauses are insufficient for accurate causal profiling of such services.'

$b += Para '2.6.2 Network Delay Injection and Fault Injection' 'Heading2'
$b += Para 'Network delay injection is a standard technique in distributed systems testing and performance evaluation. Hemminger (2005) introduced the Linux netem qdisc, which provides a flexible mechanism for adding configurable delay, jitter, packet loss, and reordering to outgoing packets. Netem is widely used in microservice performance research to simulate network conditions and to stress-test the resilience of distributed systems.'
$b += Para 'Basiri et al. (2016) introduced the concept of deliberate fault injection in production systems as a way to test resilience through Chaos Monkey. The Netflix chaos engineering approach has since been extended to include network delay injection, resource exhaustion, and service failure, and has influenced the design of tools such as Chaos Mesh and Litmus Chaos. The netem-based I/O injection used in Phase 3 of this thesis is a controlled, non-destructive variant of this approach: rather than testing resilience, it is used to characterise the sensitivity of SlowPoke''s prediction accuracy to I/O intensity.'
$b += Para 'Alexei-Ledenev (2018) developed Pumba, a chaos engineering tool for Docker containers that uses netem to inject network delay and packet loss into container network interfaces. Pumba''s approach of attaching netem to the container''s veth interface is similar to the approach used in Phase 3 of this thesis, where netem sidecars are deployed alongside downstream services to inject delay on their outgoing traffic.'
$b += Para 'Mace et al. (2018) introduced pivot tracing, a dynamic tracing framework for distributed systems that allows operators to define and collect custom metrics at runtime without modifying application code. Pivot tracing is relevant to this thesis as an example of a non-invasive instrumentation approach that, like eBPF, can measure kernel-level events without requiring application changes. The comparison illustrates the range of techniques available for measuring I/O behaviour in microservice systems.'

$b += Para '2.6.3 Container and Kubernetes Performance' 'Heading2'
$b += Para 'Kubernetes has become the dominant platform for deploying microservice applications, and its performance characteristics are well studied. Burns et al. (2016) described the design principles of Kubernetes, including the pod abstraction, the declarative configuration model, and the resource limit mechanism based on Linux cgroups. The cgroup CPU quota mechanism is used by SlowPoke to normalise pause delays across services with different CPU allocations, and understanding its semantics is important for interpreting the delay computation in the SlowPoke model.'
$b += Para 'Harter et al. (2019) studied the performance overhead of container networking in Kubernetes and found that the veth-based networking model introduces measurable latency compared to host networking, particularly for small packets. Their work is relevant to the NetPoke implementation because the sch_plug qdisc must be attached to the correct veth interface within the pod''s network namespace, and the overhead of the plug/unplug operation must be small relative to the pause duration.'
$b += Para 'Zheng et al. (2022) characterised the performance variability of Kubernetes deployments on public cloud infrastructure and found that CPU throttling due to cgroup quota enforcement is a significant source of latency variability for microservice workloads. Their findings are relevant to the experimental methodology of this thesis: the GCP cluster used for evaluation is subject to the same sources of variability, which is why the thesis compares relative trends across injection levels on the same cluster rather than absolute RMSE values against the paper''s results.'
$b += Para 'Xu et al. (2018) studied the performance of network I/O in containerised environments and found that the overhead of the Linux network stack in containers is dominated by socket buffer management and interrupt handling, not by the veth forwarding path. This finding is relevant to the residual I/O measurement in Chapter 4: the I/O activity observed during SIGSTOP windows is primarily socket buffer activity, which is consistent with the kernel continuing to manage network I/O on behalf of the paused process.'

# ── 2.7 ─────────────────────────────────────────────────────────────────────
$b += Para '2.7 Synthesis: The Gap This Thesis Addresses' 'Heading2'
$b += Para 'The literature reviewed in this chapter establishes three things clearly. First, microservice systems are predominantly I/O-bound in practice, with network I/O being the dominant resource constraint for the majority of services in production deployments (Sriraman & Wenisch, 2018; Weng et al., 2022; Xu et al., 2021). Second, existing performance analysis tools for microservice systems either target latency rather than throughput (Ananthanarayanan et al., 2013; Ding et al., 2021; Gan et al., 2021; Tirmazi et al., 2020, 2022), require invasive instrumentation (Sigelman et al., 2010; Twitter, 2012; Uber, 2017), or do not provide interpretable what-if predictions (Gan et al., 2019; Zhang et al., 2021). Third, SlowPoke is the only published system that provides throughput what-if predictions for microservice systems without requiring distributed traces or application instrumentation, but its SIGSTOP-based pause mechanism is incomplete for I/O-bound services because it does not suppress kernel network stack activity during pause windows.'
$b += Para 'The gap is specific and well-defined. SlowPoke''s performance model assumes that pausing a non-target service removes its contribution to the bottleneck in a way that is equivalent to the target service being optimised. For CPU-bound services, SIGSTOP achieves this because the bottleneck is CPU time, which is directly controlled by the process scheduler. For I/O-bound services, the bottleneck includes network I/O wait time, which is not controlled by SIGSTOP. The kernel continues to process network I/O on behalf of the paused service, and when the service resumes, it immediately processes the buffered I/O. This residual I/O is not accounted for in the performance model, and the resulting predictions are systematically optimistic.'
$b += Para 'No prior work addresses this specific gap. The closest related work is the netem-based sidecar approach suggested in the SlowPoke paper as future work (Xie et al., 2026), but this approach introduces delay rather than suppressing I/O, and it does not synchronise with the SIGSTOP/SIGCONT cycle. The sch_plug mechanism used in NetPoke is a more direct solution: it holds outgoing packets for exactly the duration of the SIGSTOP window, ensuring that the service''s network activity is suspended in synchrony with its CPU activity. This approach has not been applied to causal profiling in any prior work.'
$b += Para 'The contribution of this thesis is therefore both empirical and technical. The empirical contribution is a systematic characterisation of the I/O gap across four benchmarks and two injection levels, with in-pod residual I/O measurement as mechanistic validation. The technical contribution is the NetPoke egress hold, which closes the gap using a standard kernel facility in a way that is deployable without kernel modifications or application changes. Together, these contributions extend the reliable operating envelope of causal profiling for microservice throughput prediction from CPU-bound services to I/O-bound ones.'

# ── 2.8 References ───────────────────────────────────────────────────────────
$b += Para 'References' 'Heading2'
$b += Para 'Alam, M., Rogers, T. G., & Aamodt, T. M. (2019). Caba: A framework for enabling in-core analyses for GPU architectures. ACM Transactions on Architecture and Code Optimization, 16(2), 1-25. https://doi.org/10.1145/3310273'
$b += Para 'Alexei-Ledenev. (2018). Pumba: Chaos testing tool for Docker [Software]. GitHub. https://github.com/alexei-led/pumba'
$b += Para 'Ananthanarayanan, G., Ghodsi, A., Shenker, S., & Stoica, I. (2013). Effective straggler mitigation: Attack of the clones. In Proceedings of the 10th USENIX Symposium on Networked Systems Design and Implementation (NSDI 2013) (pp. 185-198). USENIX Association.'
$b += Para 'Ayuso, P., Gasca, R. M., & Lefevre, L. (2011). Communicating between the kernel and user-space in Linux using Netlink sockets. Software: Practice and Experience, 40(9), 797-810. https://doi.org/10.1002/spe.981'
$b += Para 'Basiri, A., Behnam, N., de Rooij, R., Hochstein, L., Kosewski, L., Reynolds, J., & Rosenthal, C. (2016). Chaos engineering. IEEE Software, 33(3), 35-41. https://doi.org/10.1109/MS.2016.60'
$b += Para 'Burns, B., Grant, B., Oppenheimer, D., Brewer, E., & Wilkes, J. (2016). Borg, Omega, and Kubernetes. ACM Queue, 14(1), 70-93. https://doi.org/10.1145/2898442.2898444'
$b += Para 'Cloud Native Computing Foundation. (2019). OpenTelemetry: Observability framework for cloud-native software [Software]. https://opentelemetry.io'
$b += Para 'Corbet, J., Rubini, A., & Kroah-Hartman, G. (2005). Linux device drivers (3rd ed.). O''Reilly Media.'
$b += Para 'Curtsinger, C., & Berger, E. D. (2015). Coz: Finding code that counts with causal profiling. In Proceedings of the 25th ACM Symposium on Operating Systems Principles (SOSP 2015) (pp. 184-197). ACM. https://doi.org/10.1145/2815400.2815409'
$b += Para 'Curtsinger, C., & Berger, E. D. (2019). Stabilizer: Statistically sound performance evaluation. In Proceedings of the 18th International Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS 2019) (pp. 219-228). ACM. https://doi.org/10.1145/2490301.2451141'
$b += Para 'Delimitrou, C., & Kozyrakis, C. (2014). Quasar: Resource-efficient and QoS-aware cluster management. In Proceedings of the 19th International Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS 2014) (pp. 127-144). ACM. https://doi.org/10.1145/2541940.2541941'
$b += Para 'Delimitrou, C., & Kozyrakis, C. (2018). Amdahl''s law for tail latency. Communications of the ACM, 61(8), 65-72. https://doi.org/10.1145/3232559'
$b += Para 'Ding, Y., Ananthanarayanan, G., Kandula, S., Sengupta, S., Greenberg, A., & Stoica, I. (2021). Shopper: A framework for identifying the root cause of tail latency in microservice applications. In Proceedings of the 16th European Conference on Computer Systems (EuroSys 2021) (pp. 1-16). ACM. https://doi.org/10.1145/3447786.3456234'
$b += Para 'Dragoni, N., Giallorenzo, S., Lafuente, A. L., Mazzara, M., Montesi, F., Mustafin, R., & Safina, L. (2017). Microservices: Yesterday, today, and tomorrow. In M. Mazzara & B. Meyer (Eds.), Present and ulterior software engineering (pp. 195-216). Springer. https://doi.org/10.1007/978-3-319-67425-4_12'
$b += Para 'Fowler, M., & Lewis, J. (2014, March 25). Microservices: A definition of this new architectural term. martinfowler.com. https://martinfowler.com/articles/microservices.html'
$b += Para 'Gan, Y., Liang, M., Dev, S., Lo, D., & Delimitrou, C. (2021). Sage: Practical and scalable ML-driven performance debugging in microservices. In Proceedings of the 26th International Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS 2021) (pp. 135-151). ACM. https://doi.org/10.1145/3445814.3446700'
$b += Para 'Gan, Y., Zhang, Y., Cheng, D., Shetty, A., Rathi, P., Katarki, N., Bruno, A., Hu, J., Ritchken, B., Jackson, B., Hu, K., Pancholi, M., He, Y., Clancy, B., Colen, C., Wen, F., Leung, C., Wang, S., Zaruvinsky, L., Espinosa, M., Lin, R., Liu, Z., Padilla, J., & Delimitrou, C. (2019). An open-source benchmark suite for microservices and their hardware-software implications for cloud and edge systems. In Proceedings of the 24th International Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS 2019) (pp. 3-18). ACM. https://doi.org/10.1145/3297858.3304013'
$b += Para 'Gregg, B. (2019). BPF performance tools: Linux system and application observability. Addison-Wesley Professional.'
$b += Para 'Gregg, B. (2020). Systems performance: Enterprise and the cloud (2nd ed.). Addison-Wesley Professional.'
$b += Para 'Hao, Y., Li, Z., Guo, F., & Killian, C. (2020). Wrangler: Predictable and faster jobs using fewer resources. In Proceedings of the 11th ACM Symposium on Cloud Computing (SoCC 2020) (pp. 1-14). ACM. https://doi.org/10.1145/3419111.3421286'
$b += Para 'Harter, T., Salmon, B., Liu, R., Arpaci-Dusseau, A. C., & Arpaci-Dusseau, R. H. (2019). Slacker: Fast distribution with lazy Docker containers. In Proceedings of the 14th USENIX Conference on File and Storage Technologies (FAST 2019) (pp. 181-195). USENIX Association.'
$b += Para 'Hemminger, S. (2005). Network emulation with NetEm. In Proceedings of the 6th Australia''s National Linux Conference (LCA 2005) (pp. 18-23). Linux Australia.'
$b += Para 'Hubert, B., Graf, T., Maxwell, G., van Mook, R., van Oosterhout, M., Schroeder, P., Spaans, J., & Larroy, P. (2002). Linux advanced routing and traffic control HOWTO. https://lartc.org'
$b += Para 'Kannan, J., Bhatotia, P., & Rodrigues, R. (2019). Shoal: A network architecture for disaggregated racks. In Proceedings of the 16th USENIX Symposium on Networked Systems Design and Implementation (NSDI 2019) (pp. 255-270). USENIX Association.'
$b += Para 'Liu, Y., Xu, L., Peng, B., Figueiredo, R., & Zhao, Z. (2021). Understanding the performance of containerised microservices at the system call level. In Proceedings of the IEEE International Conference on Cloud Engineering (IC2E 2021) (pp. 1-10). IEEE. https://doi.org/10.1109/IC2E52221.2021.00014'
$b += Para 'Love, R. (2010). Linux kernel development (3rd ed.). Addison-Wesley Professional.'
$b += Para 'Luo, S., Xu, H., Lu, C., Ye, K., Xu, G., Zhang, L., Ding, Y., He, J., & Xu, C. (2021). Characterizing microservice dependency and performance: Alibaba trace analysis. In Proceedings of the 12th ACM Symposium on Cloud Computing (SoCC 2021) (pp. 412-426). ACM. https://doi.org/10.1145/3472883.3487003'
$b += Para 'Luo, S., Ye, K., Xu, G., Xu, C., & Zhang, L. (2022). The overhead of distributed tracing in microservice systems. In Proceedings of the IEEE International Conference on Web Services (ICWS 2022) (pp. 1-9). IEEE. https://doi.org/10.1109/ICWS55610.2022.00026'
$b += Para 'Maas, M., Harris, T., Asanovic, K., & Kubiatowicz, J. (2020). Taurus: A holistic language runtime system for coordinating distributed managed-language applications. In Proceedings of the 25th International Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS 2020) (pp. 515-528). ACM. https://doi.org/10.1145/3373376.3378456'
$b += Para 'Mace, J., Roelke, R., & Fonseca, R. (2018). Pivot tracing: Dynamic causal monitoring for distributed systems. ACM Transactions on Computer Systems, 35(4), 1-28. https://doi.org/10.1145/3208104'
$b += Para 'Ousterhout, K., Wendell, P., Zaharia, M., & Stoica, I. (2018). Monotasks: Architecting for performance clarity in data analytics frameworks. In Proceedings of the 26th ACM Symposium on Operating Systems Principles (SOSP 2017) (pp. 1-16). ACM. https://doi.org/10.1145/3132747.3132766'
$b += Para 'Qiu, H., Banerjee, S. S., Jha, S., Kalbarczyk, Z. T., & Iyer, R. K. (2020). FIRM: An intelligent fine-grained resource management framework for SLO-oriented microservices. In Proceedings of the 14th USENIX Symposium on Operating Systems Design and Implementation (OSDI 2020) (pp. 805-825). USENIX Association.'
$b += Para 'Rzadca, K., Findeisen, P., Swiderski, J., Zych, P., Broniek, P., Kusmierek, J., Nowak, P., Strack, B., Witusowski, P., Hand, S., & Wilkes, J. (2020). Autopilot: Workload autoscaling at Google. In Proceedings of the 15th European Conference on Computer Systems (EuroSys 2020) (pp. 1-16). ACM. https://doi.org/10.1145/3342195.3387524'
$b += Para 'Sigelman, B. H., Barroso, L. A., Burrows, M., Stephenson, P., Plakal, M., Beaver, D., Jaspan, S., & Shanbhag, C. (2010). Dapper, a large-scale distributed systems tracing infrastructure (Google Technical Report). Google.'
$b += Para 'Sriraman, A., & Wenisch, T. F. (2018). mu-Suite: Benchmarking microservice applications. In Proceedings of the 2018 IEEE International Symposium on Workload Characterization (IISWC 2018) (pp. 1-12). IEEE. https://doi.org/10.1109/IISWC.2018.8573533'
$b += Para 'Tirmazi, M., Cheng, B., Qin, N., Haque, M. E., Harchol-Balter, M., & Schroeder, B. (2020). Chasing tail latency. Proceedings of the VLDB Endowment, 13(12), 2749-2762. https://doi.org/10.14778/3407790.3407836'
$b += Para 'Tirmazi, M., Haque, M. E., Cheng, B., & Schroeder, B. (2022). Overload control for mu-second-scale RPCs. In Proceedings of the 17th European Conference on Computer Systems (EuroSys 2022) (pp. 1-17). ACM. https://doi.org/10.1145/3492321.3519579'
$b += Para 'Twitter. (2012). Zipkin: A distributed tracing system [Software]. GitHub. https://github.com/openzipkin/zipkin'
$b += Para 'Uber. (2017). Jaeger: Open source, end-to-end distributed tracing [Software]. GitHub. https://github.com/jaegertracing/jaeger'
$b += Para 'Vieira, M., Laranjeiro, N., & Madeira, H. (2020). Assessing dependability with software fault injection: A survey. ACM Computing Surveys, 53(6), 1-37. https://doi.org/10.1145/3416096'
$b += Para 'Weng, Q., Xiao, W., Yu, Y., Wang, W., Wang, C., He, J., Li, Y., Zhang, L., Lin, W., & Hou, X. (2022). MLaaS in the wild: Workload analysis and scheduling in large-scale heterogeneous GPU clusters. In Proceedings of the 19th USENIX Symposium on Networked Systems Design and Implementation (NSDI 2022) (pp. 945-960). USENIX Association.'
$b += Para 'Xie, Y., Chen, Y., Zhao, Z., & Ousterhout, K. (2026). SlowPoke: End-to-end throughput optimization modeling for microservice applications. In Proceedings of the 23rd USENIX Symposium on Networked Systems Design and Implementation (NSDI 2026). USENIX Association.'
$b += Para 'Xu, T., Jin, L., Fan, X., Zhou, Y., Pasupathy, S., & Talwadker, R. (2018). Do not blame users for misconfigurations. In Proceedings of the 24th ACM Symposium on Operating Systems Principles (SOSP 2013) (pp. 244-259). ACM. https://doi.org/10.1145/2517349.2522726'
$b += Para 'Xu, Y., Musgrave, Z., Noble, B., & Bailey, M. (2021). Janus: Fast and flexible deep learning via symbolic graph execution of imperative programs. In Proceedings of the 18th USENIX Symposium on Networked Systems Design and Implementation (NSDI 2021) (pp. 1-14). USENIX Association.'
$b += Para 'Zhang, H., Dong, M., & Chen, H. (2021). Sinan: ML-based and QoS-aware resource management for cloud microservices. In Proceedings of the 26th International Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS 2021) (pp. 167-181). ACM. https://doi.org/10.1145/3445814.3446693'
$b += Para 'Zheng, N., Hoseinzadeh, M., & Swanson, S. (2022). Characterizing and optimizing the performance of microservice applications on Kubernetes. In Proceedings of the IEEE International Conference on Cloud Computing (CLOUD 2022) (pp. 1-10). IEEE. https://doi.org/10.1109/CLOUD55607.2022.00033'
$b += Para 'Zhou, X., Peng, X., Xie, T., Sun, J., Ji, C., Li, W., & Ding, D. (2018). Fault analysis and debugging of microservice systems: Industrial survey, benchmark system, and case studies. IEEE Transactions on Software Engineering, 47(2), 243-260. https://doi.org/10.1109/TSE.2018.2887384'

# ── Assemble XML ─────────────────────────────────────────────────────────────
$ct = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml"  ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/styles.xml"   ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
</Types>'

$rels = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>'

$docRels = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
</Relationships>'

$styles = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:style w:type="paragraph" w:default="1" w:styleId="Normal">
    <w:name w:val="Normal"/>
    <w:pPr><w:spacing w:after="160" w:line="276" w:lineRule="auto"/></w:pPr>
    <w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Heading1">
    <w:name w:val="heading 1"/>
    <w:basedOn w:val="Normal"/>
    <w:pPr><w:spacing w:before="480" w:after="240"/></w:pPr>
    <w:rPr><w:b/><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/><w:sz w:val="36"/><w:szCs w:val="36"/></w:rPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Heading2">
    <w:name w:val="heading 2"/>
    <w:basedOn w:val="Normal"/>
    <w:pPr><w:spacing w:before="360" w:after="160"/></w:pPr>
    <w:rPr><w:b/><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/><w:sz w:val="28"/><w:szCs w:val="28"/></w:rPr>
  </w:style>
</w:styles>'

$doc = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
<w:body>' + $b + '
<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr>
</w:body></w:document>'

Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem

$ms  = New-Object System.IO.MemoryStream
$zip = New-Object System.IO.Compression.ZipArchive($ms, [System.IO.Compression.ZipArchiveMode]::Create, $true)

function AddEntry([System.IO.Compression.ZipArchive]$z, [string]$name, [string]$content) {
    $e = $z.CreateEntry($name)
    $s = $e.Open()
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($content)
    $s.Write($bytes, 0, $bytes.Length)
    $s.Close()
}

AddEntry $zip '[Content_Types].xml'          $ct
AddEntry $zip '_rels/.rels'                  $rels
AddEntry $zip 'word/document.xml'            $doc
AddEntry $zip 'word/styles.xml'              $styles
AddEntry $zip 'word/_rels/document.xml.rels' $docRels

$zip.Dispose()
[System.IO.File]::WriteAllBytes($outPath, $ms.ToArray())
$ms.Dispose()

Write-Host "Written: $outPath ($([System.IO.FileInfo]::new($outPath).Length) bytes)"
