// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/simple-grpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleRequest) Reset() {
	*x = SimpleRequest{}
	mi := &file_proto_simple_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleRequest) ProtoMessage() {}

func (x *SimpleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleRequest.ProtoReflect.Descriptor instead.
func (*SimpleRequest) Descriptor() ([]byte, []int) {
	return file_proto_simple_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type SimpleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          string                 `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleResponse) Reset() {
	*x = SimpleResponse{}
	mi := &file_proto_simple_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleResponse) ProtoMessage() {}

func (x *SimpleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleResponse.ProtoReflect.Descriptor instead.
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return file_proto_simple_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *SimpleResponse) GetResp() string {
	if x != nil {
		return x.Resp
	}
	return ""
}

var File_proto_simple_grpc_proto protoreflect.FileDescriptor

const file_proto_simple_grpc_proto_rawDesc = "" +
	"\n" +
	"\x17proto/simple-grpc.proto\x12\tsimplercp\"+\n" +
	"\rSimpleRequest\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\"$\n" +
	"\x0eSimpleResponse\x12\x12\n" +
	"\x04resp\x18\x01 \x01(\tR\x04resp2J\n" +
	"\x06Simple\x12@\n" +
	"\tSimpleRPC\x12\x18.simplercp.SimpleRequest\x1a\x19.simplercp.SimpleResponseB!Z\x1fgithub.com/eniac/mucache/pkg/pbb\x06proto3"

var (
	file_proto_simple_grpc_proto_rawDescOnce sync.Once
	file_proto_simple_grpc_proto_rawDescData []byte
)

func file_proto_simple_grpc_proto_rawDescGZIP() []byte {
	file_proto_simple_grpc_proto_rawDescOnce.Do(func() {
		file_proto_simple_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_simple_grpc_proto_rawDesc), len(file_proto_simple_grpc_proto_rawDesc)))
	})
	return file_proto_simple_grpc_proto_rawDescData
}

var file_proto_simple_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_simple_grpc_proto_goTypes = []any{
	(*SimpleRequest)(nil),  // 0: simplercp.SimpleRequest
	(*SimpleResponse)(nil), // 1: simplercp.SimpleResponse
}
var file_proto_simple_grpc_proto_depIdxs = []int32{
	0, // 0: simplercp.Simple.SimpleRPC:input_type -> simplercp.SimpleRequest
	1, // 1: simplercp.Simple.SimpleRPC:output_type -> simplercp.SimpleResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_simple_grpc_proto_init() }
func file_proto_simple_grpc_proto_init() {
	if File_proto_simple_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_simple_grpc_proto_rawDesc), len(file_proto_simple_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_simple_grpc_proto_goTypes,
		DependencyIndexes: file_proto_simple_grpc_proto_depIdxs,
		MessageInfos:      file_proto_simple_grpc_proto_msgTypes,
	}.Build()
	File_proto_simple_grpc_proto = out.File
	file_proto_simple_grpc_proto_goTypes = nil
	file_proto_simple_grpc_proto_depIdxs = nil
}
